version: '3.7'
services:
    mysql_db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 3306:3306
    adminer_db:
        image: adminer:latest
        ports:
            - 8080:8080
        depends_on:
            - mysql_db